# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rrXyZm5VhJYW5GJWqJH3rY6AyKevSGU
"""

from dataclasses import dataclass


@dataclass
class CitaMedica:
    codigo: str
    paciente: str
    fecha: str
    especialidad: str
    medico: str


# Lista de citas para hacer las pruebas
lista_citas = [
    CitaMedica(
        "C001",
        "Juan Pérez",
        "2026-09-25",
        "Cardiología",
        "Dr. Pérez"
    ),

    CitaMedica(
        "C002",
        "María López",
        "2026-09-20",
        "Cardiología",
        "Dr. Gómez"
    ),

    CitaMedica(
        "C003",
        "Carlos Ruiz",
        "2026-09-28",
        "Pediatría",
        "Dr. Pérez"
    )
]


# =========================
# FUNCIONES
# =========================

def filtrar_por_especialidad(citas, especialidad):
    return list(filter(
        lambda cita: cita.especialidad.lower() == especialidad.lower(),
        citas
    ))


def filtrar_por_medico(citas, medico):
    return list(filter(
        lambda cita: cita.medico.lower() == medico.lower(),
        citas
    ))


def transformar_fechas(citas):
    return list(map(
        lambda cita: cita.fecha,
        citas
    ))


def ordenar_por_fecha(citas):
    return sorted(
        citas,
        key=lambda cita: cita.fecha
    )

import unittest

# ==========================================
# MOSTRAR REGISTRO DE CITAS
# ==========================================

print("==========================================")
print("        CITAS REGISTRADAS")
print("==========================================")

for cita in lista_citas:
    print("Código:", cita.codigo)
    print("Paciente:", cita.paciente)
    print("Fecha:", cita.fecha)
    print("Especialidad:", cita.especialidad)
    print("Médico:", cita.medico)
    print("------------------------------------------")


# ==========================================
# PRUEBAS UNITARIAS
# ==========================================

class TestCitasMedicas(unittest.TestCase):

    def setUp(self):
        self.citas = lista_citas

    def test_filtrar_cardiologia(self):
        resultado = filtrar_por_especialidad(
            self.citas,
            "Cardiología"
        )

        self.assertEqual(len(resultado), 2)

    def test_filtrar_medico(self):
        resultado = filtrar_por_medico(
            self.citas,
            "Dr. Pérez"
        )

        self.assertEqual(len(resultado), 2)

    def test_transformar_fechas(self):
        resultado = transformar_fechas(self.citas)

        self.assertEqual(
            resultado,
            [
                "2026-09-25",
                "2026-09-20",
                "2026-09-28"
            ]
        )

    def test_ordenar_por_fecha(self):
        resultado = ordenar_por_fecha(self.citas)

        self.assertEqual(
            resultado[0].fecha,
            "2026-09-20"
        )


# Ejecutar pruebas
print("\n==========================================")
print("        RESULTADO DE LAS PRUEBAS")
print("==========================================")

unittest.main(
    argv=['first-arg-is-ignored'],
    exit=False,
    verbosity=2
)